title: SoaP Hub
description: Architecture one-pagers for our products
theme: null
markdown: kramdown
permalink: pretty
collections:
  apps:
    output: true
    permalink: /apps/:name/
defaults:
  - scope:
      path: ""
      type: "apps"
    values:
      layout: app
